version: '3.8'

services:
  database-product:
    image: mysql:8.0
    container_name: order-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=tiger
      - MYSQL_USER=whatap
      - MYSQL_DATABASE=order

    volumes:
      - ./src/main/resources/db/migration/V1__init.sql:/docker-entrypoint-initdb.d/V1__init.sql
      - order-db:/var/lib/mysql

volumes:
  product-db:
